# Generated by Django 4.0.4 on 2022-05-21 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Pozitsiya',
                'verbose_name_plural': 'Pozitsiyalar',
            },
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='FISH')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', models.TextField(blank=True, verbose_name='Biografiya')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Rasm')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='O`zgartirilgan vaqti')),
                ('is_published', models.BooleanField(default=True, verbose_name='Chop etilgan')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='players.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Futbolchi',
                'verbose_name_plural': 'Futbolchilar',
            },
        ),
    ]
