# Generated by Django 4.0.4 on 2022-05-21 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_category_players_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Pozitsiya', 'verbose_name_plural': 'Pozitsiyalar'},
        ),
        migrations.AlterModelOptions(
            name='players',
            options={'verbose_name': 'Futbolchi', 'verbose_name_plural': 'Futbolchilar'},
        ),
        migrations.AlterField(
            model_name='players',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='players.category', verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='players',
            name='content',
            field=models.TextField(blank=True, verbose_name='Biografiya'),
        ),
        migrations.AlterField(
            model_name='players',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Chop etilgan'),
        ),
        migrations.AlterField(
            model_name='players',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='players',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='players',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='O`zgartirilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='players',
            name='title',
            field=models.CharField(max_length=255, verbose_name='FISH'),
        ),
    ]
